output "argocd_admin_password" {
  description = "ArgoCD admin password (auto-generated by ArgoCD on first install)"
  value       = data.kubernetes_secret_v1.argocd_initial_admin.data["password"]
  sensitive   = true
}

output "argocd_namespace" {
  description = "Namespace where ArgoCD is installed"
  value       = "argocd"
}
