apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: {{ .Values.vaultId }}
      auth:
        serviceAccountSecretRef:
          name: {{ .Values.tokenSecret.name }}
          key: {{ .Values.tokenSecret.key }}
          namespace: {{ .Values.tokenSecret.namespace }}
