{{- if .Values.onepasswordItemName }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-basic-auth
  namespace: monitoring
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: monitoring-basic-auth
    creationPolicy: Owner
  data:
    - secretKey: users
      remoteRef:
        key: {{ .Values.onepasswordItemName }}/users
{{- end }}
